### ISSUE TITLE
wrong split?

### ISSUE THREAD

**Issue by JensBoelte** [JackEdTaylor/LexOPS#5]
I have tried to use the following script to generate a stimulus set with a split condition for frequency and a control_condition for number of syllables. The script does not always generate a stimulus set according to the split conditions. Some of the items have a frequency that exceeds the set limits. Any idea what is wrong with the script or lexOPS?

Best wishes Jens

[dlexdb_results.csv](https://github.com/user-attachments/files/17281171/dlexdb_results.csv)

#Demo Paket lexOPS

myLibs <- c("LexOPS", "tidyverse")
lapply(myLibs, require, character.only = TRUE)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

#Beispiel dlexDB nur vier buchstabige Woerter

dlexDB <- read_tsv("dlexdb_results.csv", locale = locale(encoding = "UTF-8"))

colnames(dlexDB) <- c("Type", "PoSTag", "Lemma", "Silben", "AnTypeFreqN", "TypeFreqN")

dlexDB$NrSilben <- str_count(dlexDB$Silben, "-") + 1
dlexDB$TypeL <- nchar(dlexDB$Type)
dlexDB$LemmaL <- nchar(dlexDB$Lemma)

range(dlexDB$AnTypeFreqN)

stimuli <- dlexDB |>
  set_options(id_col = "Lemma") |>
  split_by(AnTypeFreqN, 10:20 ~ 200:6557) |>
  control_for(NrSilben, 0:0) |>
  generate(n = "all", match_null = "inclusive")

stimLong <- long_format(stimuli)
stimLong <- stimLong[order(stimLong$condition),]
#deskriptive Statistik
stimLong %>% group_by(condition) %>% summarise(M = mean(AnTypeFreqN),
                                               SD = sd(AnTypeFreqN),
                                               Max = max(AnTypeFreqN))

**Comment by JackEdTaylor** [comment]
Hi Jens, I think the main issue is that `dlexDB$Lemma` does not seem to uniquely identify the rows. There should really be a big warning or an error for cases like this, so I will add one for when this is detected.

If you set `id_col` to a column that has no repeats, this would address your problem. For example, if each row has a unique item, you could use the row number:

```r
stimuli <- dlexDB |>
  mutate(item = as.character(row_number()) ) |>
  set_options(id_col = "item") |>
  split_by(AnTypeFreqN, 10:50 ~ 200:6557) |>
  control_for(NrSilben, 0:0) |>
  generate(n = "all", match_null = "inclusive")
```

This produces less worrying summary statistics, e.g.:

```r
stimuli |>
  long_format() |>
  group_by(condition) |>
  summarise(
    M = mean(AnTypeFreqN),
    SD = sd(AnTypeFreqN),
    Min = min(AnTypeFreqN),
    Max = max(AnTypeFreqN)
  )
```

```
# A tibble: 2 × 5
  condition     M    SD   Min    Max
  <chr>     <dbl> <dbl> <dbl>  <dbl>
1 A1         22.7  11.4  10.0   49.4
2 A2        759.  853.  201.  4545. 
```

You could still get the Lemma column with the `long_format()` results:

```r
long_format(stimuli, include = "all")
```

*Side note on what is going on: LexOPS uses the `id_col` to identify suitable candidates. If a lemma like "Mann" has a frequency below 50 when the `PoSTag` is `"nn"`, but above 200 when `"ne"`, the `"ne"` entry may be mistakenly added to the low frequency condition because it has the same ID.*

**Comment by JackEdTaylor** [comment]
Added an error for this with commit https://github.com/JackEdTaylor/LexOPS/commit/c64dd3916933e35cdc2bb331daf46619f3cc8052
